### ISSUE TITLE
Package for f-droid

### ISSUE THREAD

**Issue by teeks99** [SebaUbuntu/android_packages_apps_Selfie#115]
This is built for Lineage OS, but could it also be delivered by f-droid for users not getting it in the OS? E.g. users without lineage?

**Comment by luk1337** [comment]
Because this is supposed to be configured for each device ( see: https://github.com/SebaUbuntu/android_packages_apps_Aperture/blob/lineage-20.0/app/src/main/res/values/config.xml ), it doesn't really make sense to distribute it on F-Droid.

**Comment by SebaUbuntu** [comment]
Also because Aperture is installed as a system app on LineageOS and signed with LineageOS keys I bet this is gonna create headaches regarding updates for users using F-Droid

**Comment by teeks99** [comment]
Okay, thanks for the explanation.

**Comment by anuraag488** [comment]
@SebaUbuntu I think you guys have already thought about this but I'm still requesting. Make those config.xml options available somewhere in advanced settings to user and let device maintainers to provide default values.

**Comment by SebaUbuntu** [comment]
No.
