### ISSUE TITLE
Spanish translations not approved yet on Crowdin.

### ISSUE THREAD

**Issue by miguelcanosantana** [SebaUbuntu/android_packages_apps_Selfie#118]
I would like to add some spanish translations to this project. Although there is a strings.xml file, most of the LineageOS app are translated via Crowdin. But I can't find the Crowdin for this app neither.

Should I contribute with a pull request? Or is there any Crowdin specific section that I'm missing.
Thanks :)

**Comment by luk1337** [comment]
https://translate.lineageos.org/

**Comment by miguelcanosantana** [comment]
Thanks for the link. But as I was telling I can't manage to find the aperture app in there.

**Comment by luk1337** [comment]
![image](https://user-images.githubusercontent.com/6830979/219392705-e4bfb2a6-4a25-4f0e-b946-7766cf739306.png)

**Comment by miguelcanosantana** [comment]
Thanks. Then it's already translated. However I'm not seeing it in the final app.

**Comment by luk1337** [comment]
Translations were last imported on Feb 13 (see: https://github.com/LineageOS/android_packages_apps_Aperture/commits/lineage-20.0).

**Comment by miguelcanosantana** [comment]
Okey, something is wrong with the translations.
"ast-rES" is for Astorian, not main Spanish. It's like the automatic imported translations only imported Astorian ones.
The code for plain spanish is "es".
![image](https://user-images.githubusercontent.com/55782155/219394591-fec191b3-fab7-4835-a4fd-9c2b7a495945.png)

**Comment by luk1337** [comment]
![image](https://user-images.githubusercontent.com/6830979/219396195-739ceb34-1f64-4a0a-a105-3c2f4f22dd35.png)
seems like it's 100% translated but not approved?

**Comment by miguelcanosantana** [comment]
Okey good, I'm changing the title then.

**Comment by luk1337** [comment]
I closed the issue since it's out of scope.

**Comment by miguelcanosantana** [comment]
That's fine.
