### ISSUE TITLE
Aparture is not included in the latest LineageOS build.

### ISSUE THREAD

**Issue by ghost** [SebaUbuntu/android_packages_apps_Selfie#129]
Hello there.

I'm have just installed the latest official LineageOS rom but that doesn't include this camera on my device (Redmi 8A / Mi439), instead that bundles another camera having the package name "com.android.camera2". Is this intentional or an accidental mistake? If this is unintentional then where should I report it?

Thank you for your time.

**Comment by luk1337** [comment]
https://github.com/LineageOS/android_device_xiaomi_mithorium-common/commit/f8ae997d34aca7b700a4803746d9a41896bd7113
