### ISSUE TITLE
Handling one-time photo/video for other apps

### ISSUE THREAD

**Issue by SebaUbuntu** [SebaUbuntu/android_packages_apps_Selfie#28]
I don't even know where to start implementing that, but camera apps installed as system app should be able to handle other apps requests for a single photo/video (e.g. when uploading a photo from Chrome)

This can be done later once we start testing the app inline with LineageOS

**Comment by luk1337** [comment]
Seems like we need to check if intent action is `MediaStore.ACTION_IMAGE_CAPTURE` and then write result to `MediaStore.EXTRA_OUTPUT` Uri.

**Comment by luca020400** [comment]
Currently we already have these intents in the Manifest but they aren't handled
If ACTION_IMAGE_CAPTURE or ACTION_IMAGE_CAPTURE_SECURE are set we need to dumb down the UI to allow only taking the photo

There is also ACTION_VIDEO_CAPTURE
